### ISSUE TITLE
Broken config patch

### ISSUE THREAD

**Issue by strizhechenko** [tintinweb/scapy-ssl_tls#100]
After installation I got:
```
In [1]: from scapy.all import rdpcap
  File "/usr/local/lib/python2.7/site-packages/scapy/config.py", line 388
    "sctp", "vrrp", "ipsec", "lltd", "vxlan", "ssl_tls" ]    contribs = dict()
                                                                    ^
SyntaxError: invalid syntax
```

It seems like somewhere `'\n'` is missed.

**Comment by tintinweb** [comment]
Hi @strizhechenko, thanks for the report.
what os are you on?

**Comment by strizhechenko** [comment]
Hi! Meh, it was so long ago so I forgot it :(
Most probably it's CentOS 6, maybe latest MacOS.

**Comment by strizhechenko** [comment]
I'll try to reproduce it this weekend and report here full scenario

**Comment by tintinweb** [comment]
Hi @strizhechenko,

the `scapy/config.py` patching magic attempts to find the `load_layers` list in the scapy config files and follows until the end of the list `]`. We then do a backwards search to find the last `"` just before the `]`. If that line does not contain `ssl_tls` we're inplace appending `, "ssl_tls"]` to that line without ever touching any line-endings. According to this procedure, we never ever change nor add linebreaks. 

Are you using a custom scapy version or a version that already messed with the `load_layers` list? As long as the `load_layers` list is not misformatted (e.g. end of the list is a line with only a `]`) it should do fine.

* CNR on ubuntu 16.04 pip
* CNR on centos 7
* did not test osx
* CNR with dos line endings, unix line endings, manual modifications to config.py (found an unrelated corner-case were we would not patch the line if `]` stands for itself on a separate line)

I'll close this issue for now. Feel free to reopen it if you can reproduce it and I'm happy to rewrite that hacky code 👍 

cheers
tin
