### ISSUE TITLE
Server key Exchange

### ISSUE THREAD

**Issue by sujith-chilled** [tintinweb/scapy-ssl_tls#102]
Any one have any sample code for generating SKE message from server ?

**Comment by alexmgr** [comment]
Hi @sujith-chilled,

I did this a while back, but looks like I never put this in the example folder. Can't remember if it required changes to `scapy-ssl_tls` itself.
Anyway, you can start by modifying `rsa_server.py` under `examples` to support SKE. If you encounter any bugs, I can fix the backend code.

**Comment by alexmgr** [comment]
@sujith-chilled I just added this in #113 (only DHE right now).
Give it a shot if it's still relevant to you (see `examples/server_dhe.py)`
