### ISSUE TITLE
Examples not working correctly?

### ISSUE THREAD

**Issue by ril3y** [tintinweb/scapy-ssl_tls#105]
Perhaps I am missing something.
https://github.com/tintinweb/scapy-ssl_tls/blob/master/examples/client_hello_rsa.py#L32

But any example with the TLSHandshakes class is not working as I cannot find it?
`
# create TLS Handhsake / Client Hello packet
    p = TLSRecord() / TLSHandshakes(handshakes=[TLSHandshake() / TLSClientHello(cipher_suites=[TLSCipherSuite.RSA_WITH_AES_128_CBC_SHA])])
`

Where is TLSHandshakes?

**Comment by alexmgr** [comment]
Hi @ril3y,

`TLSHandshakes` is in `master` only. So if you've installed through PIP, you'll have to look at the examples at the 1.2.3 git tag.

@tintinweb might be time to cut a new release?

**Comment by tintinweb** [comment]
@alexmgr agree, all the cool features are in 2.0 (master) right now :). Please review the drafted release and I'll make sure to have it tested and released over the next couple of days. Note we're breaking backwards compatibility with the 2.0 (tls1.3 features)

**Comment by tintinweb** [comment]
fyi - just released v2.0.0 to pypi. 

cheers
tin
