### ISSUE TITLE
Support for Scapy 2.4

### ISSUE THREAD

**Issue by wasilukm** [tintinweb/scapy-ssl_tls#117]
Scapy 2.4 is close to be released. It will deliver significant features and upgrades.
Are there any plans for scapy-ssl_tls to support this release?

**Comment by tintinweb** [comment]
Hi @wasilukm,

scapy already broke some interfaces with the v2.3.3 update some time ago. thats why we pin the scapy version to <2.3.3 (see requirements.txt). Whether we're going to support scapy 2.4 more or less depends on how stable the new api stays and how much effort it takes to accommodate the changes. No investigation planned yet. 

cheers,
tin

**Comment by wasilukm** [comment]
Hi @tintinweb 

Thank you for the quick reply. It seems that current [Scapy](https://github.com/secdev/scapy/tree/master/scapy/layers/tls) code has quite extended support for TLS.
It may be worth checking.

**Comment by gpotter2** [comment]
Hi @tintinweb,

Scapy 2.4.0 was released a few days ago. The API should remain stable from now on, and it contains python 3 support (no need to support scapy3k, which btw is becoming more than outdated :/ )

Regards

**Comment by googlebleh** [comment]
Currently working on it. Is there anything else I should try to do besides get everything in `tests/` to pass?

**Comment by robgom** [comment]
Can anybody tell me why isn't this code merged to scapy project itself?

Regards,
Robert

**Comment by tintinweb** [comment]
merged with #136 , thanks @googlebleh @wasilukm
