### ISSUE TITLE
Missing Example: Dissect TLSClientHello (pcap)

### ISSUE THREAD

**Issue by confshared** [tintinweb/scapy-ssl_tls#118]
I find this example, but the code is not in the examples section. Can you include it please? is there a pcpa dissector for ServerHello?

**Comment by tintinweb** [comment]
Hi @confshared,

Please elaborate on what example you are missing.
If you're looking in a pcap example see [examples/sessionctx_sniffer.py](https://github.com/tintinweb/scapy-ssl_tls/blob/master/examples/sessionctx_sniffer.py) which also loads pcaps (auto-dissects for port 443, 4433 - see `bind_layers` in `ssl_tls.py`).

There's also some use-cases hidden in the [unit-tests ](https://github.com/tintinweb/scapy-ssl_tls/blob/master/tests/test_ssl_tls.py)

cheers,
tin
