### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in C:\Users\e\AppData\Local\Temp\pip-build-ir7moadc\scapy\

### ISSUE THREAD

**Issue by confshared** [tintinweb/scapy-ssl_tls#120]
I am tryint o install scapy-ssl_tls in Windows and I use Pyathon 3.6. 
I run: `py -m pip install scapy-ssl_tls`
I get:
`Command "python setup.py egg_info" failed with error code 1 in C:\Users\myuser\AppData\Local\Temp\pip-build-ir7moadc\scapy\`

Cna you help please?

**Comment by tintinweb** [comment]
closed - dup #121
