### ISSUE TITLE
pycrypto can not be installed in ubuntu

### ISSUE THREAD

**Issue by confshared** [tintinweb/scapy-ssl_tls#124]
I am sorry this question may not be directly relevant. But this library is required. pycrypto can't be installed in ubuntu. Plz advise.
```
x@x-VirtualBox:~/scapy-2.3.1$ sudo apt-get install pycrypto
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package pycrypto

```

**Comment by tintinweb** [comment]
Hi @confshared,

please stick to the code of conduct and do not duplicate your own tickets, stick to one ticket/issue per topic and add your notes as comments to this ticket otherwise this will become unmanagable. (see your other issues #121)
