### ISSUE TITLE
Error: TLSHanshakes is not defined

### ISSUE THREAD

**Issue by confshared** [tintinweb/scapy-ssl_tls#126]
I am tryin to reproduce the SCSV example in your examples:
https://github.com/tintinweb/scapy-ssl_tls/blob/master/examples/SCSV_fallback_test.py

I tried this smaller program built based on the example:

```
from __future__ import division
import sys
try:
	import scapy.all as scapy
except ImportError:
	import scapy

try:
	from scapy_ssl_tls.ssl_tls import *
except ImportError:
	from scapy.layers.ssl_tls import *

import socket
import itertools

print ("program start")

if __name__=="__main__":
	target = "google.com"
	port = 443

	PROTOS = [p for p in TLS_VERSIONS.values() if p.startswith("TLS_") or p.startswith("SSL_3")]

	
	print(PROTOS[1]) #PROTOS[1] is TLS 1.0
	protoVersion = PROTOS[1]	
	TLS_FALLBACK_SCSV_SUPPORTED = False
	
	#create tcp socket
	s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	s.connect((target,443)) 
	print("connected")

	#create a TLS handshake
	p = TLSRecord(version=protoVersion) / \
	    TLSHandshakes(handshakes=[TLSHandshake() /
		                      TLSClientHello(version= protoVersion,
		    		                     cipher_suites=range(0xff) + [0x5600],)])

	p.show()

```
When I run the code, I get:
```
WARNING: No route found for IPv6 destination :: (no default route?)
program start
TLS_1_0
connected
Traceback (most recent call last):
  File "tls-scanner-v1.py", line 36, in <module>
    TLSHandshakes(handshakes=[TLSHandshake() /
NameError: name 'TLSHandshakes' is not defined

The TLSHandshakes is in the example. How can I figure our what are the available functions in this module? I do not have manual to double check. Please, can you point to me what is wrong?
```
I also ran the same exact code you posted and got the same error. I will appreciate your help. I apologize for the spam.

**Comment by tintinweb** [comment]
Hi @confshared,

*long story*
our master branch is ahead of the currently released v1.2.x branch thats why the master branch examples here do not match. Please use the examples oft the branch corresponding to your installed release version - in your case likely [scapy-ssl_tls v1.2.3](https://github.com/tintinweb/scapy-ssl_tls/tree/release/1.2.3)

*quick fix*
Anyway, I've just release v2.0.0 (which is not fully backward compatible with v1.2.3) to pypi which as of now is in sync with master (examples). You just need to upgrade your scapy-ssl_tls version and that should be fine then.
 
dup #105
