### ISSUE TITLE
can't import layer ssl_tls: No module named 'ssl_tls_registry'

### ISSUE THREAD

**Issue by sk1985** [tintinweb/scapy-ssl_tls#138]
```python
>>> import scapy
>>> from scapy.layers.ssl_tls import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/scapy/layers/ssl_tls.py", line 11, in <module>
    import ssl_tls_registry as registry
ImportError: No module named 'ssl_tls_registry'
>>> 
```

**Comment by tintinweb** [comment]
Hey @sk1985,

that's odd. working fine with the latest version in my py2env. would you mind checking if the ssl_tls_registry.py is in the `scapy/layers` folder?

```python
>>> import scapy
>>> from scapy.layers.ssl_tls import *
>>>
>>> import scapy.layers.ssl_tls
>>> scapy.layers.ssl_tls.registry
<module 'scapy.layers.ssl_tls_registry' from '/mnt/c/stuff/workspace/git/scapy-ssl_tls/.env27/local/lib/python2.7/site-packages/scapy/layers/ssl_tls_registry.pyc'>
```

**Comment by sk1985** [comment]
testuser@sk-automation:/usr/local/lib/python3.5/dist-packages/scapy_ssl_tls$ ls
__init__.py  __pycache__          ssl_tls_crypto.py    ssl_tls.py
pkcs7.py     ssl_tls_automata.py  ssl_tls_keystore.py  ssl_tls_registry.py

**Comment by tintinweb** [comment]
@sk1985 we do not have official python3 support yet. if you want to experiment use the py3compat branch.

the issue is not reproducible on py27 and the issue is lacking more information.

cheers,
tin
