### ISSUE TITLE
ValueError: 'fields_desc' in __slots__ conflicts with class variable

### ISSUE THREAD

**Issue by tukiasingh** [tintinweb/scapy-ssl_tls#144]

**Comment by tintinweb** [comment]
Hi @tukiasingh,

py3 support is experimental. please report back if this also happens with py2.

cheers,
tin

**Comment by tukiasingh** [comment]
Thanks a ton for replying back.
Please help me understand this I heard scapy 2.4.0 is compatible with
python3 and your current scapy_ssl_tls master version is compatible with
scapy 2.4.*

Then why I am getting this error. I am new to python, so may be I am asking
a stupid question.

BTW, by when do you think we can have compatible version for py3.

Regards,
Vijay
