### ISSUE TITLE
I need a help for Encrypt the communication of the Modbus protocol using AES and SSL Socket programming in python. 

### ISSUE THREAD

**Issue by PraveenKumarSoni** [tintinweb/scapy-ssl_tls#146]
Actually here is two machine Server and Client which work on the Modbus/TCP protocol. Now I want to Encrypt and Decrypt the communication of Server and Client by putting two machines A & B between client and server. When a client operates the server then Modbus/TCP packet will go to machine B, Now machine B will extract the TCP buffer(Modbus data) and encrypt it with AES encryption and send it to machine A using SSL socket programming, And now machine A will decrypt the data of Modbus/TCP protocol and it should send to server so that we can secure the communication which is happening between client and server. And vice versa for the server to client communication.

Please, guys, help me.
Thanks.

**Comment by tintinweb** [comment]
@PraveenKumarSoni appears like you're looking for default tcp proxy with tls/ssl support.

**Comment by PraveenKumarSoni** [comment]
@tintinweb Yes..!!
I don't want the proxy setup. Because it will affect latency and I don't want to decrease latency of this setup. Actually, my code is not working. If you want then I can send you so that you can help me. Please mention your email id.

Thanks.
