### ISSUE TITLE
how can i control the condition to count how much TLS protocol packages

### ISSUE THREAD

**Issue by always-raining** [tintinweb/scapy-ssl_tls#148]
how can i control the condition to count how much TLS protocol packages, and i also want to know how to extract some information in the ##SSL/TLS##, such as the length of the package. can anyone help me? thank you very much!

**Comment by tintinweb** [comment]
Hi @always-raining,

1) not sure what you are looking for.
2) this is scapy functionality. for details refer to the scapy documentation. e.g. this is how to get the tlsheartbeat length `resp[TLSHeartBeat].length`. works with any layer like: `var[sublayer].attribute`
