### ISSUE TITLE
Problem with [ClientHello].extensions_length

### ISSUE THREAD

**Issue by lespla** [tintinweb/scapy-ssl_tls#40]
I have several cases in that I can't see the  [ClientHello].extensions_length but I can see it
 with wireshark.  I've been looking for source code and this field is conditional and I think the condition doesn't work well.
I have attached several capture files with extension file chenged, from pcap to png
Best regards
![https_ipv4](https://cloud.githubusercontent.com/assets/4354214/8720788/27be19ca-2bb5-11e5-8cf9-9a40a36c3a35.png)
![https_ipv6](https://cloud.githubusercontent.com/assets/4354214/8720789/2b06dd10-2bb5-11e5-924e-17aa59444a34.png)

**Comment by alexmgr** [comment]
Hi lespla,

Thanks for your report and pcaps. Yes, the extension dissection has given us some headaches earlier.
I can't look at this right now, but maybe Tin can (he's generally all over this ;)).

Otherwise, will look at it in the upcoming weeks.

Alex

**Comment by tintinweb** [comment]
Hi lespla,

yeah, conditional fields I love them :)

I've proposed a fix for this with #41. Please check out the branch and let me know if that fixes the problem for you.
Will add some unit tests within the next days or so to make sure this is properly tested.

Thanks for your report.

tin

**Comment by lespla** [comment]
It seems to work well. For me you can close the bug
