### ISSUE TITLE
help finding the decripted HTTPS data

### ISSUE THREAD

**Issue by gunvant3** [tintinweb/scapy-ssl_tls#60]
Hi there,

I am having trouble getting the decrypted "application data" from a pcap file using "scapy-ssl_tls/examples/sessionctx_sniffer.py" 

I get "<TLSCiphertext data=...(the encrypted data)" BUT I am looking for "decrypted record"

All my parameters for the main work, i.e. my pcap file, .key file, and host and port numbers.

Please respond at your earliest convenience.

Thank you

**Comment by tintinweb** [comment]
Hi,

Please provide more information and we'll be happy to investigate your issue. 

* which ciphersuite was negotiated? (RSA/AES?)
* any output for sessionctx_sniffer?
* minimal sample pcap + privkey. Note: In your own intrest, do **NOT** provide productive keys or pcaps with sensitive information. 

- tin

**Comment by tintinweb** [comment]
no response, closing.
