### ISSUE TITLE
No output from 'sessionctx_sniffer' example

### ISSUE THREAD

**Issue by ALSchwalm** [tintinweb/scapy-ssl_tls#63]
First let me say that this is an awesome project, I have a lot of things I can't wait to use it for.

However, as I play around, I've run into an issue with 'sessionctx_sniffer' example. I ran a wireshark capture on a connection from the 'full_rsa_connection_with_application_data' example to an openssl server I was running on localhost. I then passed the pcap and private key to the sniffer example. However there is no output after the "load servers private key".

After some investigation, this appears to be because while the packets appear to have an SSL/TLS layer when I `show` them, `haslayer(SSL)` returns `False`. This causes [this line](https://github.com/tintinweb/scapy-ssl_tls/blob/master/examples/sessionctx_sniffer.py#L204) to be an empty list. My suspicion is that the reassembly is damaging the packets in some way, but I have not been able to find the root of the problem.

I can provide the capture and private key (I just generated it for this, it doesn't need to be kept secret) if that would be helpful.

EDIT: This is some kind of import error. If I install through `setup.py` and remove the imports from the project dir, this works.

**Comment by tintinweb** [comment]
might be related to #62. I've seen this error before with scapy being installed by pip and trying to run an example from the project dir.

There is some black magic vodoo going on when an example tries to load the library. it first tries to load it from the local source path and if that fails it will load it from `scapy.layers` assuming that it was installed via pip or setup.py. 

I guess it would probably be best to just get rid of that and always load it from scapy or site-packages.
