### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by ca2r0tXb0y** [tintinweb/scapy-ssl_tls#66]
Hi,
When I ran test_ssl_tls.py and test_ssl_tls_crypto.py, I got following errors:
`python test_ssl_tls.py`
FAIL: test_encrypted_layer_is_decrypted_if_required (__main__.TestTLSDissector)

Traceback (most recent call last):
  File "test_ssl_tls.py", line 175, in test_encrypted_layer_is_decrypted_if_required
    self.assertTrue(server_finished_records.haslayer(tls.TLSHandshake))
AssertionError: 0 is not true

Ran 39 tests in 1.487s

FAILED (failures=1)

`python test_ssl_tls_crypto.py`
FAIL: test_fixed_crypto_data_matches_verify_data (__main__.TestTLSSessionCtx)

Traceback (most recent call last):
  File "test_ssl_tls_crypto.py", line 174, in test_fixed_crypto_data_matches_verify_data
    self.assertEqual(client_verify_data, binascii.hexlify(tls_ctx.get_verify_data()))
AssertionError: 'e23f73911909a86be9e93fdb' != '12003ac89553b7a233da64b9'

Ran 35 tests in 0.379s

FAILED (failures=1)

And i don't know where goes wrong?

**Comment by ca2r0tXb0y** [comment]
It seems `TLSSessionCtx().get_verify_data()` doesn't calculate EncryptedHandshakeMessage right.

**Comment by alexmgr** [comment]
Hi,

These unit-tests run fine for me on master:
```
(scapy-ssl_tls)amoneger@silvertip scapy-ssl_tls/tests (master) » git log -n 1 | grep commit
commit 870e4721b8ea816a7e1c196edb6c161015d83e60
(scapy-ssl_tls)amoneger@silvertip scapy-ssl_tls/tests (master) » python test_ssl_tls_crypto.py
...................................
----------------------------------------------------------------------
Ran 35 tests in 0.485s

OK
(scapy-ssl_tls)amoneger@silvertip scapy-ssl_tls/tests (master) » python test_ssl_tls.py       
WARNING: No route found for IPv6 destination :: (no default route?)
.......................................
----------------------------------------------------------------------
Ran 39 tests in 1.845s

OK
```

Can you provided a bit more details on your setup? Which branch you're on, install from pip/git, scapy version, ...

Would be appreciated,
Alex

**Comment by ca2r0tXb0y** [comment]
Thanks for replying, and I know where goes wrong.
I install from pip, and it gives those errors.
When i uninstall it and install from source, everything goes right.
It seems that version from pip and source both are 1.2.2, but i don't know why results are different.

**Comment by tintinweb** [comment]
the version on pip is 1.2.2 and the upcoming release is 1.2.3 (current master; here's a diff https://github.com/tintinweb/scapy-ssl_tls/compare/v1.2.2...master). I've updated the version on master to reflect that its actually at v1.2.3.
