### ISSUE TITLE
pip installation does not work

### ISSUE THREAD

**Issue by hackers-terabit** [tintinweb/scapy-ssl_tls#68]
I have python3 installed,I can't install scapy_ssl-tls with pip or pip3:
```
 # pip install scapy_ssl-tls
Collecting scapy-ssl-tls
  Using cached scapy-ssl_tls-1.2.2.tar.gz
Collecting scapy (from scapy-ssl-tls)
  Using cached scapy-2.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-f333v30u/scapy/setup.py", line 35
        os.chmod(fname,0755)
                          ^
    SyntaxError: invalid token
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-f333v30u/scapy/

```

**Comment by tintinweb** [comment]
`scapy-ssl_tls` currently does not support `python3`. In order to install scapy and scapy-ssl_tls run `pip` with python2.x.

//The actual problem here is that with python3 the notation for octal values changed from `0<>` to `0o<>/0O<>` see [Abstract PEP-3127](https://www.python.org/dev/peps/pep-3127/).

**Comment by hackers-terabit** [comment]
Thank you but I wanted it to be the central feature of my script which is already about 500 lines of python3. I won't ask you to support python3 but I would appreciate any pointers on how to get it working python3. I was unable to find any other existing module to monitor TLS handshakes in python.

**Comment by tintinweb** [comment]
atm there are no plans to port it to python3. Also see https://github.com/tintinweb/scapy-ssl_tls/issues/39

**Comment by hackers-terabit** [comment]
ok,thank you for addressing this,I'll close the issue.

**Comment by hackers-terabit** [comment]
fyi , I forked it for python3 ,seems to be working fine for now https://github.com/hackers-terabit/scapy-ssl_tls-python3

**Comment by tintinweb** [comment]
we were discussing porting scapy to python3 either with a compatibility layer or as a different branch in the other issue. Howerver, there's no no one working on this atm but we'd appreciate if someone would jump in starting the initial port to python3 making sure that unittests pass and file a PR for review. 

- tin
