### ISSUE TITLE
Remove *pycrypto* dependency

### ISSUE THREAD

**Issue by alexmgr** [tintinweb/scapy-ssl_tls#74]
_[pycryptodome](https://github.com/Legrandin/pycryptodome)_ provides a drop in replacement for _pycrypto_.
It also supports GCM and CCM modes with the same interface, which would make it trivial to implement for us

**Comment by tintinweb** [comment]
👍 lets give it a try on a separate branch and check if it breaks anything. I can test it on py26 with windows (at least easy_install was able to compile/install it :))

**Comment by alexmgr** [comment]
Already did.
It works mostly out of the box on *nix. Check `pycryptodome` branch if interested.

Will allow GCM/CCM mode for TLS1.3, + DSA kex.

**Comment by tintinweb** [comment]
I'll check that branch and report back.

**Comment by alexmgr** [comment]
GCM will require a refactor of `CryptoContainer` and `TLSSecurityParameters`.

Cipher intialization and state tracking has to move to the `CryptoContainer`, which will have to be subclassed per cipher modes... Not illogical in a sense, but have to introduce some kind of `CryptoContainer` factory to return the right instance for a given cipher mode and TLS version.
Guess we can have 2 `CryptoContainer`s per TLSContext and go from there.

TLS implementation is such a mess. At least TLS 1.3 removes that stupid explicit IV idea.

**Comment by alexmgr** [comment]
OK, got GCM mode working for SHA-256 default PRF. Will send out a PR soon.

Will build on the PR for other PRFs.

**Comment by alexmgr** [comment]
Done as part of #77
