### ISSUE TITLE
ECDHE not working when server hello, certificate, server key exchange are encapsulated in single record layer

### ISSUE THREAD

**Issue by perrin-ay** [tintinweb/scapy-ssl_tls#83]
First let me say terrific work with this! 
The problem i ran into was while running the example client script using ECDHE . It works fine with certain servers and does not with others. Ostensibly this problem appears to be predicated on how the server responds. From packet captures( attached , please open with wireshark) when server is replying  with server hello , server key exchange in separate record layers , the ssl handshake completes successfully and application data is exchanged. However when a server replies with server hello, certificate , server key exchange all encapsulated in one record layer as evidenced in the first tcp stream in the capture file, the client script errors out. At this time , from viewing the tls_ctx,  i see all crypto.server.ecdh attributes are none and from the code it looks like if p.haslayer(tls.TLSServerECDHParams) condition is not True.

         params.negotiated.version=TLS_1_2
         params.negotiated.ciphersuite=ECDHE_RSA_WITH_AES_256_CBC_SHA
         params.negotiated.key_exchange=ECDHE
         params.negotiated.encryption=('AES', 32, 'CBC')
         params.negotiated.mac=SHA
         params.negotiated.compression=NULL
         crypto.client.enc=None
         crypto.client.dec=None
         crypto.server.enc=None
         crypto.server.dec=None
         crypto.client.rsa.privkey=None
         crypto.client.rsa.pubkey=None
         crypto.server.rsa.privkey=None
         crypto.server.rsa.pubkey=<_RSAobj @0x7f8d5b7f7b00 n(2048),e>
         crypto.client.dsa.privkey=None
         crypto.client.dsa.pubkey=None
         crypto.server.dsa.privkey=None
         crypto.server.dsa.pubkey=None
         crypto.client.dh.x=None
         crypto.client.dh.y_c=None
         crypto.server.dh.p=None
         crypto.server.dh.g=None
         crypto.server.dh.x=None
         crypto.server.dh.y_s=None
         crypto.client.ecdh.curve_name=None
         crypto.client.ecdh.priv=None
         crypto.client.ecdh.pub=None
         crypto.server.ecdh.curve_name=None
         crypto.server.ecdh.priv=None
         crypto.server.ecdh.pub=None
         crypto.session.encrypted_premaster_secret=None
         crypto.session.premaster_secret="\x03\x03\xda\x8e`\xb1.\xf9)\x1c#x\xef\x1d\x0eE\xfb\xe1\xe2\xa2\xd33y\xc1\xd3';\xb2\x9c,S\x04\xbf%\x88\x89\xd9\xe3\xc8\xb2r\xe0\xc4\x18\xc3\xd0z\x10"
         crypto.session.master_secret=None
         crypto.session.randombytes.client='X6j\xfc\x15n\xd6/#\xf4\x0e%\xd3\xfb\x07\xde;\xc2\xd0\xd0d\x99\x84\xd4\xe0\xc2\x18J\xff\x97Sm'
         crypto.session.randombytes.server="X6j\xfcK\x1d?!\x1fp\xceg}\x1dA\xa3\xf2\x89\xed4\xd1\xa5k{>\xf0\xfd\xd4'\x9f\xfe\xf6"
         crypto.session.key.client.mac=None
         crypto.session.key.client.encryption=None
         crypto.session.key.cllient.iv=None
         crypto.session.key.server.mac=None
         crypto.session.key.server.encryption=None
         crypto.session.key.server.iv=None
         crypto.session.key.length.mac=None
         crypto.session.key.length.encryption=None
         crypto.session.key.length.iv=None
>

Traceback (most recent call last):
  File "ecdhessl_scapytest.py", line 62, in <module>
    tls_client(server)
  File "ecdhessl_scapytest.py", line 49, in tls_client
    tls_client_key_exchange(sock)
  File "ecdhessl_scapytest.py", line 30, in tls_client_key_exchange
    client_key_exchange = TLSRecord(version=tls_version) / TLSHandshake() / sock.tls_ctx.get_client_kex_data()
  File "/usr/local/lib/python2.7/dist-packages/scapy_ssl_tls/ssl_tls_crypto.py", line 585, in get_client_kex_data
    return tls.TLSClientKeyExchange(ctx=self) / tls.TLSClientECDHParams(data=self.get_client_ecdh_pubkey(val))
  File "/usr/local/lib/python2.7/dist-packages/scapy_ssl_tls/ssl_tls_crypto.py", line 566, in get_client_ecdh_pubkey
    ec_curve = ec_reg.get_curve(self.crypto.server.ecdh.curve_name)
  File "/usr/local/lib/python2.7/dist-packages/tinyec/registry.py", line 95, in get_curve
    if name.lower() == k.lower():
AttributeError: 'NoneType' object has no attribute 'lower'

Thanks!

[cap_esdhe.txt](https://github.com/tintinweb/scapy-ssl_tls/files/610476/cap_esdhe.txt)

**Comment by alexmgr** [comment]
Hi @perrin-ay,

Thanks for taking the time to write the detailed bug report.
Stacked handshakes are super painful to deal with, and I thought we addressed that for good a while back with #13 ;).
I have an idea why this is happening, but I don't have time to address this right now. Fixing `insert` in `ssl_tls_crypto` to iterate on handshakes instead of records should do the trick. I'll pick this up when i have a bit of time.

Thanks again!

**Comment by perrin-ay** [comment]
Sounds great. Thank you much!

**Comment by alexmgr** [comment]
Hi @perrin-ay,

I have had to fix this in order to get TLS 1.3 to dissect properly. Could you chekout the tls1.3 branch and try it out?

I have had to slightly change the interface of the `TLSHandshake` layer to make this generic enough, so you'll need to slightly adapt your script. For example, a client hello now becomes:
```
TLSRecord(version=tls_version) / TLSHandshakes(handshakes=[TLSHandshake() /
        TLSClientHello(version=tls_version, cipher_suites=[TLSCipherSuite.ECDHE_RSA_WITH_AES_128_GCM_SHA256, ])])
```

You can also now create stacked handshakes, ala java, but more importantly dissection works properly in all cases.

Would you mind giving this a try and letting me know if this fixes your problem?

Thanks

**Comment by perrin-ay** [comment]
Hey @alexmgr , 

This fixed the problem. Thanks again for looking into this ! cheers

**Comment by alexmgr** [comment]
Thanks for verifying!
