### ISSUE TITLE
Sending large overflow values (packet > 65535bytes)

### ISSUE THREAD

**Issue by Avidor** [tintinweb/scapy-ssl_tls#95]
Hi,

Some poor (or old) SSL implementations are vulnerable to DOS by sending large overflow values in the Client Hello packet. Since these implementations don't support tcp window scaling and wait for the entire client hello packet (even though it might be much larger than 32kb) it can keep a connection busy even without completing a ssl handshake.

I tried doing this test using scapy ssl tls. I modified gmt_unix_time header to support variable length strings  and did a client hello with a gmt_unix_time="a" * 10000000, but I am getting a Fragmentation Error as the packet exceeds 65535 bytes. 

I would like to know if it is possible to send such large overflowing values or is it a limitation?

Thanks!

**Comment by tintinweb** [comment]
Hi @Avidor,

While the `tlsrecord.size` field (short) can be up to 65k [rfc2246 6.2.1 Fragmentation](https://tools.ietf.org/html/rfc2246#section-6.2.1) recommends a maximum records size of 16k. Our implementation of [TLSRecord](https://github.com/tintinweb/scapy-ssl_tls/blob/master/scapy_ssl_tls/ssl_tls.py#L451) currently enforces this limit and if you exceed `TLSRecord.MAX_LEN` a `TLSFragmentationError` will be thrown. However, you're free to override `TLSRecord.MAX_LEN` to fit your needs but be aware, this is a class attribute and your change will be shared with all other instances of `TLSRecord`. Note that you cannot exceed 65k as this is the maximum value the records size field can hold.

Also note, that [TLSClientHello.gmt_unix_time](https://github.com/tintinweb/scapy-ssl_tls/blob/master/scapy_ssl_tls/ssl_tls.py#L707) is not a good candidate for adding random data as it is a fixed length 4 byte integer field and adding 10m 'a' will likely just result in creating an invalid hello message. Your best bet would be planting your payload as valid extensions to the hello message.

Here's a modification to [client_hello_valid.py](https://github.com/tintinweb/scapy-ssl_tls/blob/master/examples/client_hello_valid.py) that will build 'valid structured' 65k client hello by adding a lot of garbage padding extensions.

```python
# create TLS Handhsake / Client Hello packet
TLSRecord.MAX_LEN = 2**16
p = TLSRecord() / TLSHandshakes(handshakes=[TLSHandshake() /
                                            TLSClientHello(compression_methods=py2range(0xff)[::-1],
                                                           cipher_suites=py2range(0xff),
                                                           extensions=[TLSExtension() / TLSExtPadding("a"*100)]*622)])

print(len(str(p)))
# 65502
```

**Comment by Avidor** [comment]
Hi @tintinweb 
Thanks for the reply.
It does answer my question but this is a limitation when it comes to fuzzing. If the TLSRecord size is 65k MAX it will not be able to provide sufficient fuzzing. Some SSL implementation will only fail on very large overflow values. 

As for gmt_unix_time, the test was inspired by Codenomicon Defensics TLS fuzzing suite. It sends a long string (10 million bytes) instead of the proper unix time. On scapy_tls I edited gmt_unix_time to be a variable length string and attempted to send a 10 million bytes string and that obviously failed.

**Comment by tintinweb** [comment]
Hi @Avidor,

`scapy-ssl_tls` does not limit you in any way to produce *invalid tls records*. 
The rfc specifies `TLSRecord.length` to be an unsigned int (max=2^16). However, that does not mean you cannot override it or hint an any record size you want.

The following (scapy-ssl_tls 1.2.3.2 compatible) example builds a 91k `TLSClientHello` by adding garbage TLSServerNameExtensions and setting all the length fields to max to prevent scapy from autocalculating the length. You have to manually set the length fields as scapy will likely complain that the length exceeds the maximum possible value for the record length (remember, 2**16-1).

```python
TLSRecord.MAX_LEN = 2**64-1  # satisfy the fragmentation size check.. any high int.
# create TLS Handhsake / Client Hello packet
# note that we set all length fields to ushort max as we're going to exceed that anyway.
p = TLSRecord(length=2**16-1)/TLSHandshake(length=2**16-1)/TLSClientHello(compression_methods=range(0xff)[::-1],
                                            cipher_suites=range(0xff),
                                            extensions_length=2**16-1,
                                            extensions=[TLSExtension() / TLSExtServerNameIndication(server_names=[TLSServerName(data="www.dummysite.com")])]*3500)

p.show()
print(len(str(p)))
#91814
```

Codenomicon `gmt_unix_time` overflow leaves some questions as they're overflowing a fixed size 4 byte field and therefore garbling the next fields with non tls compliant stuff. Thats kind of the crowbar way to do things and a decent stack is likely going to abort the connection once you provide something non-tls-ish :) Would probably be similar to something like `TLSRecord(length=2**16-1)/TLSHandshake(length=2**16-1)/RandString()` in scapy-ssl_tls.

Hope that makes sense :)

cheers 
tin

**Comment by Avidor** [comment]
thanks @tintinweb that's what I was looking for.
